chimpas/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart'),
    path('cart_add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart_remove/<int:id>/', views.cart_remove, name='cart_remove'),
    path('product-plus/<int:id>/', views.cart_plus_product, name='cart_plus_product'),
    path('product-minus/<int:id>/', views.cart_minus_product, name='cart_minus_product'),
]

chimpas/chimpas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('users/', include('users.urls')),
    path('shirts/', include('shirt.urls')),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chimpas/cart/models.py
from django.conf import settings

from django.db import models
from shirt.models import Shirts


class Cart (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Shirts, on_delete=models.CASCADE)
    product_qty = models.IntegerField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

chimpas/cart/forms.py
from django import forms

#PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
#SIZE = [
      #  ('XS', 'Xs'),
       # ('S', 'S'),
       # ('M', 'M'),
       # ('L', 'L'),
        #('XL', 'Xl'),
   # ]

class CartAddProductForm(forms.Form):

    #sizes = forms.TypedChoiceField( choices=SIZE )
    quantity = forms.IntegerField(min_value= 1, label='Количество', widget=forms.NumberInput(attrs={'class': 'inpt_class'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

chimpas/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shirt.models import Shirts
from .cart import Cart
from .forms import CartAddProductForm


#@require_POST
def cart_add(request, id):
    cart = Cart(request)
    product = get_object_or_404(Shirts, id=id)
    #form = CartAddProductForm(request.POST)
    #if form.is_valid():
        #cd = form.cleaned_data
    cart.add(product=product, quantity=1, update_quantity=1)
    return redirect('cart:cart')


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Shirts, id=id)
    cart.remove(product)
    return redirect('cart:cart')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart.html', {'cart': cart})


def cart_plus_product(request, id):
    cart = Cart(request)
    product = get_object_or_404(Shirts, id=id)
    cart.product_plus(product)
    return redirect('cart:cart')

def cart_minus_product(request, id):
    cart = Cart(request)
    product = get_object_or_404(Shirts, id=id)
    cart.product_minus(product)
    return redirect('cart:cart')


#def cart_plus_size(request, id):
    #cart = Cart(request)
    #product = get_object_or_404(Shirts, id=id)
    #cart.product_plus(product)
    #return redirect('cart:cart')

#def cart_minus_size(request, id):
    #cart = Cart(request)
    #product = get_object_or_404(Shirts, id=id)
    #cart.product_minus(product)
    #return redirect('cart:cart')

chimpas/templates/about.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        CHIMPAS магазин футболок CHIMPAS - это магазин прикольных футболок, маек и толстовкок.
Футболки CHIMPAS отличаются не только оригинальным дизайном, но и отличным качеством.
Все футболки изготавливаются из высококачественных материалов и имеют длительный срок службы.
В нашем магазине представлены футболки на все случаи жизни.
Вы можете выбрать футболку для повседневной носки, футболку для занятий спортом, футболку на каждый день, футболку-поло, футболки для девушек, подростков и детей.
    </div>
</body>
</html>
{% endblock content %}

chimpas/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>CHIMPAS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      @keyframes gradient {
          0% {
                background-position: 0% 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }
    </style>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </head>
  <body>

  <div class="d-flex">
      <div class="col">
          <div class="b-example-divider b-example-vr w-100" style="background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
	background-size: 400% 400%;
	animation: gradient 15s ease infinite;
	height: 100%; "></div>
      </div>
      <div class="col-10">



          <header class="p-3 mb-3 border-bottom">
            <div class="container">
              <div class="d-flex  align-items-center  justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                  <a href="{% url 'home' %}"><img height="60px" width="60px" src="{% static '/images/home.png/' %}"></a>
                </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center ">
            <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Главная</a></li>
            <li><a href="{% url 'about' %}" class="nav-link px-2 link-dark">О нас</a></li>
            <li><a href="{% url 'contacts' %}" class="nav-link px-2 link-dark">Контакты</a></li>
                {% if user.is_superuser %}
                    <li><a href="{% url 'shirt_new' %}" class="nav-link px-2 link-dark">Добавить</a></li>
                {% endif %}
        </ul>
          <div>
               <button type="submit" onclick="window.location.href = '{% url 'cart:cart' %}'" class="btn btn-success btn-lg nav-link px-4">Корзина</button>
          </div>
        <div class="dropdown text-end" id="navbarCollapse">
            {% if user.is_authenticated %}
                <a class="d-block text-decoration-none dropdown-toggle btn btn-outline-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.username }}
                </a>
                <ul class="dropdown-menu text-small">
                    <li><a class="dropdown-item" href="{% url 'user_edit' user.pk %}">Изменить данные</a></li>
                    <li><a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a></li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Выход</a></li>
                </ul>
            {% else %}
                <form class="ml-auto">
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary">Войти</a>
                </form>
            {% endif %}
        </div>
      </div>
    </div>
  </header>



          {% block content %}
          {% endblock %}



          <div class="container">
              <footer class="py-3 my-4">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                  <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
                  <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
                  <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
                  <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                  <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
                </ul>
                <p class="text-center text-muted">&copy; 2022 Company, Inc</p>
              </footer>
          </div>



          <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>



      </div>
      <div class="col">
          <div class="b-example-divider b-example-vr w-100" style="background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
	background-size: 400% 400%;
	animation: gradient 15s ease infinite;
	height: 100%;" ></div>
      </div>
  </div>
  </body>
</html>

chimpas/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}

{% csrf_token %}

<style>
  .hidden{
	display: none!important;
}
.form-field{
	width:250px;
	display: inline-block;
	padding: 5px;
}
.col-lg-4, .col-lg-6, .col-lg-8, .col-lg-12{
	margin-top: 10px;
}
.thumbnail{
	width: 100%;
	height: 200px;
	-webkit-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
    -moz-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
    box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
}
body{
	background-color: hsl(0, 0%, 98%);
}

h1,h2,h3,h4,h5,h6{
	color:hsl(0, 0%, 30%);
}

.box-element{
	box-shadow:hsl(0, 0%, 80%) 0 0 16px;
	background-color: #fff;
	border-radius: 4px;
	padding: 10px;

}
.thumbnail{
	width: 100%;
	height: 200px;
	-webkit-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
    -moz-box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
    box-shadow: -1px -3px 5px -2px rgba(214,214,214,1);
}
.chg-quantity{
	width: 12px;
	cursor: pointer;
	display: block;
	margin-top: 5px;
	transition:.1s;
}

.chg-quantity:hover{
	opacity: .6;
}
.btn:hover {
	box-shadow: 0 2px 5px rgba(1, 1, 0, 1.45);
}

</style>

 <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Вернуться обратно</a>
     <a href="{% url 'cart:cart' %}" style="float:right; " class="btn btn-success">Оформить заказ</a>
     <th><h5>Товаров: <strong>{% with total_items=cart|length %} {{ total_items }} {% endwith %} </strong></h5></th>
			<th><h5>Стоимость: <strong> {{ cart.get_total_price }} Руб.</strong></h5></th>
    </div>
    <br> <br>
<table class="table">
  <thead>
    <tr>
        <th scope="col">Товар</th>
        <th scope="col">Название
        </th><th scope="col">Цена за шт.</th>
        <th scope="col">Размер</th>
        <th scope="col">Количество</th>
        <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart %}
            {% with product=item.product %}
    <tr>

      <td><img height="100" width="100" class="row-image" src="{{ product.image.url }}" ></td>
        <td>{{ product.name }}</td>
        <td>{{ item.price }} Руб.</td>
        <td>
            {{ item.size }}
        </td>
        <td>
            <a href="{% url 'cart:cart_minus_product' product.id %}" class="btn">-</a>
            {{ item.quantity }}
            <a href="{% url 'cart:cart_plus_product' product.id %}" class="btn">+</a>
        </td>
        <td>{{ item.total_price }} Руб.</td>

  {% endwith %}
        {% endfor %}

  </tbody>
</table>



{% endblock content %}

chimpas/templates/contacts.html
{% extends 'base.html' %}
{% block content %}

<body>
<div class="d-flex ">
<div class="fon" >
    <div class="container" style="margin-left: 80px;">
        <h1>Контакты</h1><br>
        <h3>Есть вопрос? Задай его в нашем телеграме @chimpas</h3><br>
        <h5>Другие варианты связи с нами:</h5>
        <li><span>Телефон +791111111</span>
        <li><span>Почта chimpas@mail.ru</span>
        <li><span>Адрес магазина: г.Челябинск, ул.Ленина, д.23</span>
        <li><span>Время работы магазина: 10:00 - 21:00</span><br><br>

        <h5>Наши соц. сети:</h5>
        <li><span>Группа Вконтакте</span>
        <li><span>Инстаграм</span>
        <li><span>Телеграм</span>
        <li><span>Whats up</span>

    </li>
    </div>

</div>
<div style="margin-left: 80px; margin-top: 30px;">
    <div style="overflow:hidden;">
        <iframe src="https://yandex.ru/map-widget/v1/-/CCUnEIXVdD" width="560" height="400" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe></div>

</div>




</div>
</body>
<br><br><br><br>
<br><br><br><br><br>
<br>

{% endblock content %}

chimpas/templates/home.html
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>

 {% block title %}Home{% endblock %}
    {% block content %}

    <!--<div class="container">
        skgldfhgljrso;hj;oruto;hrwghoru
        <img src="{% static '/images/img.png/' %}">
    </div>-->
<div class="container">
    <div class="container-fluid">
        <div class="row">

 {% for shirt in object_list %}
        <div class="col-md-4 mb-4 pb-4">
            <div class="card" style="width: 80%;">
              <img src="{{ shirt.image.url }}" class="card-img-top" alt="tilt" height="290px"
                   onclick="window.location.href = '{% url 'shirt_detail' shirt.pk %}'">
              <div class="card-body">
                <h5 class="card-title">{{shirt.name}}</h5>
                <p class="card-text">{{shirt.price}}₽</p>
                <a href="{% url 'shirt_detail' shirt.pk %}" class="btn btn-primary">Посмотреть</a>
              </div>
            </div>
        </div>
            {% endfor %}

    </div>
    </div>
</div>
{% endblock %}
</body>

</html>

chimpas/templates/shirt_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Удалить футболку</h1>
        <div style="display:inline-block;">
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger ml-3" type="submit">Удалить</button>
            </form>
        </div>
    </div>
{% endblock content %}

chimpas/templates/shirt_detail.html
{% extends 'base.html' %}
{% block content %}
            <div class="container">

                    <h1 style="float: right;">{{ shirts.price }}₽</h1>
                    <h1>{{ shirts.name }}</h1>
                <img src="{{ shirts.image.url }}" alt="tema klop" width="500px" height="590px">
                    <p class="card-text text-break">{{ shirts.description }}</p>
                {{ shirts.sizes }}
                {{ form_shirts }}
                    <button type="submit" onclick="window.location.href = '{% url 'cart:cart_add' shirts.pk %}'" class="btn btn-success btn-lg">В корзину</button>
                {% if user.is_superuser %}
                    <button type="submit" onclick="window.location.href = '{% url 'shirt_edit' shirts.pk %}'" class="btn btn-warning btn-lg">Изменить</button>
                    <button type="submit" onclick="window.location.href = '{% url 'shirt_delete' shirts.pk %}'" class="btn btn-danger btn-lg">Удалить</button>
                {% endif %}
            </div>
{% endblock content %}

chimpas/templates/shirt_edit.html
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% extends 'base.html' %}
  {% load crispy_forms_tags %}
  {% block content %}
  <div class="container">
      <h1>Изменение</h1>
            <div style="display:inline-block;">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary ml-3" type="submit">Изменить</button>
                </form>
            </div>
            <div style="display:block;">
                {% if img_obj %}
                    <h3>Успешно изменено: {{ img_obj.name }}</h3>
                    <img src="{{ img_obj.image.url }}" alt="connect" style="max-height:300px">
                {% endif %}
            </div>
  </div>
  {% endblock %}
</body>
</html>

chimpas/templates/shirt_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% extends 'base.html' %}
  {% load crispy_forms_tags %}
  {% block content %}
  <div class="container">
      <h1>Новая футболка</h1>
            <div style="display:inline-block;">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary ml-3" type="submit">Добавить</button>
                </form>
            </div>
            <div style="display:block;">
                {% if img_obj %}
                    <h3>Успешно загружено: {{ img_obj.name }}</h3>
                    <img src="{{ img_obj.image.url }}" alt="connect" style="max-height:300px">
                {% endif %}
            </div>
  </div>
  {% endblock %}
</body>
</html>

chimpas/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Зарегистрироваться</button>
    <a href="{% url 'login' %}" class="btn btn-primary">Войти</a>
</form>
{% endblock %}
</body>
</html>

chimpas/templates/success_order.html
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Вернуться обратно</a>
     <h1>Заказ успешно оформлен</h1>
     <!--<th><h5>Товаров: <strong>{% with total_items=cart|length %} {{ total_items }} {% endwith %} </strong></h5></th>
			<th><h5>Стоимость: <strong> {{ cart.get_total_price }} Руб.</strong></h5></th>-->
    </div>

</body>

chimpas/templates/user_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% extends 'base.html' %}
    {% block content %}

        <h1>Изменить информацию о себе</h1>
        <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Обновить"/>
        </form>




    {% endblock content %}
</body>
</html>